/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

public class App {
  public static void main(String[] args) {

    System.out.println("--------------------------");
    System.out.println("     주차 관리 시스템     ");
    System.out.println("--------------------------");

    System.out.printf("동: ");
    System.out.println(108);

    System.out.printf("호수: ");
    System.out.println(1704);

    System.out.printf("이름: %s", "홍길동");
    System.out.println();

    System.out.printf("H.P: %s", "010-0000-0000\n");

    System.out.printf("차량번호: " + "24모 3736\n");

    System.out.println("차량보유현황: " + "2");

    System.out.printf("거주여부: %b", true);

  }
}
